### ISSUE TITLE
A2C derivative for mean is not implemented

### ISSUE THREAD

**Issue by ThGravo** [astooke/rlpyt#75] opened 2019-11-12 10:23 UTC
```
2019-11-12 11:18:32.850181  | a2c_pong_0 Optimizing over 1250 iterations.
Traceback (most recent call last):
  File "example_3.py", line 80, in <module>
    n_parallel=args.n_parallel,
  File "example_3.py", line 62, in build_and_train
    runner.train()
  File "//rlpyt/rlpyt/runners/minibatch_rl.py", line 196, in train
    opt_info = self.algo.optimize_agent(itr, samples)
  File "//rlpyt/rlpyt/algos/pg/a2c.py", line 38, in optimize_agent
    loss.backward()
  File "//lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "//lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: derivative for mean is not implemented
```

**Comment by bmazoure** [comment] 2019-11-12 15:08
Which Torch version are you running?

**Comment by ThGravo** [comment] 2019-11-13 23:29
I'm on Arch and got the latest package installed: `community-testing/python-pytorch-cuda 1.3.1-2`

**Comment by bmazoure** [comment] 2019-11-14 22:00
Could it be that https://github.com/astooke/rlpyt/blob/master/rlpyt/algos/pg/a2c.py#L70-L73 the `valid_mean` has issues with differentiation? What if you just put `torch.mean`?

**Comment by astooke** [comment] 2019-11-18 17:19
Oh, this is strange?  Any news?

Yeah inside `valid_mean()` it calls the tensor's method: `tensor.mean(dim=dim)`, maybe some kind of tensor issue but `torch.mean(tensor, dim=dim)` would work?

This is surprising.

**Comment by MatthewChang** [comment] 2019-11-20 18:14
I'm having the same issue on torch version `1.3.0+cu92`. It reproduces just running example 3 with the A2C or PPO algorithms.

**Comment by MatthewChang** [comment] 2019-11-20 21:00
Okay, the issue is `torch.mean(tensor,dim=())` doesn't have the gradient defined, if you just call `torch.mean(tensor)` when there is no dimension, then it works. I'm assuming that's the desired behavior when there is no dimension specified.

**Comment by astooke** [comment] 2019-12-11 23:20
OK thanks for the catch and fix!  This must be a change from 1.1.  Will make this update soon to keep up with pytorch.

**Comment by tarungog** [comment] 2019-12-21 07:26
https://github.com/pytorch/pytorch/pull/29199

It's a pytorch bug that's fixed on master only recently

**Comment by astooke** [comment] 2020-02-26 01:21
OK if I understand correctly, this is a pytorch issue and no change is needed in rlpyt.  Closing, but please reopen if that's wrong.

**Closed by astooke** 2020-02-26 01:21 UTC
